export enum NotificationType {
    STATUS_CHANGE_REQUEST = "STATUS_CHANGE_REQUEST",
    STATUS_CHANGE_APPROVED = "STATUS_CHANGE_APPROVED",
    STATUS_CHANGE_REJECTED = "STATUS_CHANGE_REJECTED",

    Info = "INFO",
    Warning = "WARNING"
}
